name: Sync dev to main after merge to main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  sync-dev:
    if: github.event.pull_request.merged == true && github.head_ref =='dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev

      # Authenticate as GitHub App
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.UPDATE_PROTECTED_APP_ID }}
          private_key: ${{ secrets.UPDATE_PROTECTED_PRIVATE_KEY }}

      - name: Pull from main
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          git pull origin main
          git push
